//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by est.rc
//
#define IDCANCEL2                       3
#define IDCANCEL3                       4
#define IDD_ABOUTBOX                    100
#define IDD_OAE                         101
#define IDD_PAVIM                       102
#define IDD_DIASNC                      103
#define IDD_TALPAVI                     104
#define IDD_CANTCEN                     106
#define IDC_CHENIV                      108
#define IDB_SPLASH                      114
#define IDD_DESENHARPERFIL              118
#define IDD_DESSECOES                   119
#define ID_TAREFASECOES                 120
#define ID_TAREFAGREIDE                 121
#define IDD_ENTRAPONTOGREIDE            122
#define IDD_PONTOGREIDE                 123
#define IDR_MAINFRAME                   128
#define IDR_EDITAR                      128
#define IDR_ESTTYPE                     129
#define IDD_CALCMEDICAO                 130
#define IDS_STRING130                   130
#define IDR_ESTREL                      130
#define IDD_IGUALDADES                  131
#define ID_TAREFAPONTOSGEO              132
#define IDD_CALCNOTA                    133
#define IDD_PEGADIR                     135
#define IDD_DESPONTOSGEO                135
#define IDR_HTML_DIACALCLIMPEZA         140
#define IDD_CONFIG_PROJ                 142
#define IDD_ARQNOVO                     145
#define IDR_PROJETOS                    162
#define IDD_TERPON                      166
#define IDR_SUBTITULO                   167
#define IDR_PROJREC                     170
#define IDD_IGUAL                       173
#define IDD_PROGRESS                    177
#define IDD_SECTIPO                     178
#define IDD_NIVELAM                     179
#define IDD_CURVER                      180
#define IDD_CURHOR                      181
#define IDD_GRADI                       182
#define IDD_ALASAR                      188
#define IDD_OAC                         191
#define IDD_PROJETO                     192
#define IDD_CALCTERR                    194
#define IDD_INSTALAR                    195
#define IDD_ABRIRMEDICAO                196
#define IDD_CRIARMEDICAO                197
#define IDD_NIVELAMENTO                 198
#define IDD_CALCTERRENO                 200
#define IDD_CURVASVERTICAIS             201
#define IDD_CURVASHORIZONTAIS           202
#define IDD_TRESPONTOS                  203
#define IDD_ALASARPAS                   204
#define IDD_DESGREIDETOOL               205
#define IDR_DESSECAO                    206
#define IDD_TALUDECAB                   210
#define IDD_PONTO                       214
#define IDD_ENTRAPONTO                  215
#define IDD_PROCURARSECAO               220
#define IDD_DESLIZANTES                 222
#define IDR_DESSECAO2                   222
#define IDD_TALUDES                     223
#define IDR_DESGREIDE                   223
#define IDD_TALUDESPAVIM                224
#define IDD_GRADIENTES                  225
#define IDD_DESSECOESTOOL               227
#define IDR_DESSECAO3                   230
#define IDR_DESSECAO4                   231
#define IDD_SELECSECAO                  231
#define IDD_CONFDESGREIDE               231
#define IDD_SELGREIDE                   232
#define IDR_DESPONTOSGEO                232
#define IDD_CONFDESMEDICAO              238
#define IDD_VOLUMES                     240
#define IDD_CALCVOLUMES                 241
#define IDD_SUPERFICIE                  242
#define IDD_SECCIONAR                   243
#define IDD_CALCGEOMETRICO              244
#define IDD_PONTOSGEO                   245
#define IDD_AUXDESPONTOS                246
#define IDD_PONGEOMETRICO               247
#define IDD_DEFBOR_ACITOPOG             250
#define IDD_CORES                       251
#define IDD_CORESDESGEOM                251
#define IDD_CORESDESGREIDE              251
#define IDD_TERRTRIANGULADO             252
#define IDD_SECTRIAN                    253
#define IDD_CONFDESGEOM                 254
#define IDD_DIALOG1                     255
#define IDD_CORESDESGEOMETRICO          255
#define IDD_DIALOG2                     256
#define IDD_EDITACH                     257
#define IDD_ROTACIONAR                  258
#define IDD_ESTACACOTA                  259
#define IDD_ENTRACOORDXY                260
#define IDD_OBRASARTECORRENTES          261
#define IDD_OBRASARTEESPECIAIS          262
#define IDD_CALCNOTAVOLUMESDIRETO       263
#define IDD_GERARDXFGEO                 264
#define IDD_GERARDXFGRE                 265
#define IDD_GERARDXFSEC                 266
#define IDD_DESLIZANTESGEOM             267
#define IDD_CALCGEORESECCIONADIRETO     268
#define IDD_CALCGEOMETRICO1             269
#define IDD_DIAGERARCN                  270
#define IDD_DIACALCSECAVULSAS           271
#define IDR_IDD_DIAGERARCN1             273
#define IDD_NOVARESTRICAO               276
#define IDD_DIACALCSUPERF               278
#define IDD_DIALOG3                     279
#define IDD_DIALOG4                     280
#define IDD_DIAMONOLOGO                 280
#define IDD_DIALOG5                     281
#define IDW_VER_PROCURAR                501
#define IDM_VER_ESCALAS                 502
#define IDD_INICIO_RELATORIOS           600
#define IDD_REL_NOTA_SERVICO_TERRAPLANAGEM 601
#define IDD_REL_PROJ_GEOMETRICO         602
#define IDD_REL_PROJ_GEOMETRICO_DETALHADO 603
#define IDD_REL_PROJ_GREIDE             604
#define IDD_REL_NOTA_SERVICO_PAVIM      605
#define IDD_REL_TERRENO_PRIMITIVO       606
#define IDD_REL_VOLUMES_TERRAPLANAGEM   607
#define IDD_REL_SECOES_AVULSAS          608
#define IDD_REL_AREA_TALUDES            609
#define IDD_REL_AREA_LIMPEZA            610
#define IDD_FIM_RELATORIOS              650
#define IDD_GET_PATH                    651
#define IDB_FILE_TYPES                  652
#define IDD_SECOESAVULSAS               652
#define IDD_SECAVUL                     653
#define IDD_DIACALCTALUDES              654
#define IDD_DIACALCLIMPEZA              655
#define IDD_LIMPEZA                     656
#define IDD_LIMPA                       657
#define IDD_EMPOL                       658
#define IDD_EMPOLA                      658
#define IDC_EDIESTINI                   1000
#define IDC_LIST                        1000
#define IDC_NOMEPROJ                    1001
#define IDC_EDIESTFIM                   1001
#define IDC_DIR                         1002
#define IDC_RADATUAIS                   1002
#define IDC_RADACUMULADA                1002
#define ID_AJUDA                        1003
#define IDC_LINHA1                      1003
#define IDC_LIST1                       1003
#define IDC_RADRECALC                   1003
#define IDC_RADPARCIAL                  1003
#define IDC_ADD                         1003
#define IDNAO                           1004
#define IDC_LINHA2                      1004
#define IDC_COMBO1                      1004
#define IDC_RADUSRNIV                   1004
#define IDC_NUMMEDICAO                  1004
#define IDC_REMOVE                      1004
#define IDSIM                           1005
#define IDC_LINHA3                      1005
#define IDC_CHECK1                      1005
#define IDC_REMOVE_ALL                  1005
#define IDC_ARQUIVOS                    1006
#define IDC_DESARESTAS                  1006
#define IDC_ADD2                        1006
#define IDC_SUBTITULO                   1008
#define IDC_DESCRISPE                   1008
#define IDC_ADD3                        1008
#define IDC_PROGRESS                    1009
#define IDC_PAUSA                       1009
#define IDC_UPDATE                      1009
#define IDC_DESCIRCULO                  1009
#define IDC_SAIR                        1009
#define IDC_NOMELOGRA                   1010
#define IDC_TXTPROG                     1010
#define IDC_DESCRUZ                     1010
#define IDC_PAUSA2                      1010
#define IDC_PROCURAR                    1011
#define IDC_CHE_VARRERPROJETO           1011
#define IDC_CANCELAR                    1012
#define IDC_AJUDA2                      1013
#define IDC_OK                          1014
#define IDC_AJUDA3                      1014
#define IDC_CALCTUDO                    1015
#define IDC_INICIAR                     1016
#define IDC_COMPLETO                    1018
#define IDC_INSERT_BEFORE               1018
#define IDC_BUTTON1                     1019
#define IDC_ORIGEM                      1020
#define IDC_BUTTON3                     1020
#define IDC_DESTINO                     1021
#define IDC_CANCEL                      1021
#define IDC_STAESTINI                   1022
#define IDC_BUTTON2                     1022
#define IDC_STAESTFIM                   1023
#define IDC_PROGRESS1                   1023
#define IDC_COORN                       1024
#define IDC_EDIIGINI                    1024
#define IDC_EDIIGFIM                    1025
#define IDC_AJUDA                       1026
#define IDC_STAIGINI                    1026
#define IDC_EQUIPAR                     1027
#define IDC_STAIGFIM                    1027
#define IDC_EQUICURHOR                  1028
#define IDC_STAARQUIVOS                 1028
#define IDC_STATICO                     1029
#define IDC_STATICO2                    1030
#define IDC_EQUITAN                     1030
#define IDC_CHETER                      1030
#define IDC_COORE                       1031
#define IDC_STAPRIORI                   1031
#define IDC_VALEST                      1032
#define IDC_RADPRINIV                   1032
#define IDC_AZIMUTE                     1033
#define IDC_RADPRITER                   1033
#define IDC_EQUIOAE                     1034
#define IDC_CHESECTRI                   1034
#define IDC_EMPRESA                     1035
#define IDC_CHEINCLUIR                  1035
#define IDC_RADPRiSECTRI                1035
#define IDC_EQUIOAE2                    1036
#define IDC_STAINCLUIR                  1036
#define IDC_ESTINI                      1036
#define IDC_VALEST2                     1037
#define IDC_EXECUTANDO                  1037
#define IDC_ESTFIM                      1037
#define IDC_INICIARCALCMED              1038
#define IDC_EXECUTADO                   1038
#define IDC_EXECUTANDO2                 1038
#define IDC_LISTMEDICAO                 1039
#define IDC_CHSOLEITURA                 1040
#define IDC_EDIT2                       1041
#define IDC_EDIT3                       1042
#define IDC_EDIT4                       1043
#define IDC_EDIT                        1044
#define IDC_EDIT23                      1045
#define IDC_EDIT6                       1046
#define IDC_EDIT7                       1047
#define IDC_EDIT8                       1048
#define IDC_EDIT9                       1049
#define IDC_EDIT10                      1050
#define IDC_EDIT24                      1051
#define IDC_EDIT26                      1052
#define IDC_EDIT27                      1053
#define IDC_EDIT28                      1054
#define IDC_EDIT1                       1057
#define IDC_COORY                       1058
#define IDC_VOLMASSCORTE                1058
#define IDC_N                           1058
#define IDC_EDIT13                      1058
#define IDC_R                           1058
#define IDC_EDCOTA                      1058
#define IDC_VOLTOTCORTE                 1059
#define IDC_EDIT15                      1059
#define IDC_LC                          1059
#define IDC_EDIT5                       1060
#define IDC_E                           1060
#define IDC_SE                          1060
#define IDC_VOLACUMCORTE                1060
#define IDC_VOLMASSATERRO               1061
#define IDC_COTA                        1061
#define IDC_SL                          1061
#define IDC_EDIT25                      1061
#define IDC_VOTOTATERRO                 1062
#define IDC_DESCRICAO                   1062
#define IDC_EDIT12                      1062
#define IDC_CORBORDOS                   1062
#define IDC_CORFUNDO                    1063
#define IDC_VOACUMATERRO                1063
#define IDC_EDIT14                      1064
#define IDC_VOLMASSATERROEMP            1064
#define IDC_CORCN                       1064
#define IDC_CORFUNDO2                   1065
#define IDC_VOACUMATERROEMP             1065
#define IDC_EDIT16                      1066
#define IDC_CORARESTAS                  1066
#define IDC_VOTOTATERROEMP              1066
#define IDC_EDIT11                      1067
#define IDC_EDIT17                      1067
#define IDC_CORCRISTASPES               1067
#define IDC_EDIT18                      1068
#define IDC_CORMALHA                    1068
#define IDC_EDIT19                      1069
#define IDC_EDIT20                      1070
#define IDC_CORFUNDO3                   1071
#define IDC_EDIT21                      1072
#define IDC_EDIT22                      1073
#define IDC_COORX                       1076
#define IDC_INICIARCALC                 1083
#define IDC_STX                         1084
#define IDC_STY                         1085
#define IDC_STI1                        1086
#define IDC_STI2                        1087
#define IDC_STY2                        1088
#define IDC_STY1                        1089
#define IDC_RATERRENO                   1090
#define IDC_RAPROJETO                   1091
#define IDC_X                           1092
#define IDC_Y                           1093
#define IDC_I1                          1094
#define IDC_I2                          1095
#define IDC_SECAO                       1096
#define IDC_IG                          1096
#define IDC_EDISECAO                    1097
#define IDC_DESLIZANTE                  1098
#define IDC_VALOR                       1099
#define IDC_DESLIZANTE2                 1100
#define IDC_VALOR2                      1101
#define IDC_STE                         1101
#define ID_VER_FERRAMENTAS              1102
#define ID_VER_COORDENADAS              1103
#define IDM_VER_PONTO                   1118
#define IDC_MBOK                        1119
#define IDC_ESTACA                      1120
#define IDC_Y1                          1121
#define IDC_Y2                          1122
#define IDC_APARAR_EXTENDER             1124
#define IDC_LIST2                       1126
#define IDC_SINCRONIZAR                 1128
#define IDC_GABARITARPROJ               1129
#define IDC_RAMEDICAO                   1130
#define IDC_DESPROJETO                  1130
#define IDC_VSECCORTE                   1131
#define IDC_DESTERRENO                  1131
#define IDC_VSECATERRO                  1132
#define IDC_DESMALHA                    1132
#define IDC_VOLUMES                     1133
#define IDC_COTAR                       1133
#define IDC_VSECATERROEMP               1133
#define IDC_GERAR                       1134
#define IDC_ATUALIZARSECOES             1134
#define IDC_SECCIONAR                   1136
#define IDC_NUMDESCPONTO                1137
#define IDC_VSECCORTE2                  1137
#define IDC_COMPENSACAOLATERAL          1137
#define IDC_BORDOS                      1141
#define IDC_ACTOPOG                     1142
#define IDC_ACITOPOG                    1147
#define IDC_EQUIDIS                     1148
#define IDC_TEXTCORFUNDO                1149
#define IDC_CORTERRAP                   1150
#define IDC_PAVIMENTO                   1151
#define IDC_DESPAVIMENTO                1151
#define IDC_TEXTCORFUNDO2               1152
#define IDC_MONOSTATICO                 1152
#define IDC_CORTERRAP2                  1153
#define IDC_MONOSTATICO2                1153
#define IDC_PAVIMENTO2                  1154
#define IDC_TEXTCORFUNDO3               1155
#define IDC_CORTERRAP3                  1156
#define IDC_PAVIMENTO3                  1157
#define IDC_DESSECOES                   1159
#define IDC_DESPIXEL                    1160
#define IDC_DESPONTOS                   1161
#define IDC_EQUIDISTANCIA               1162
#define IDC_MOSTRARDESC                 1163
#define IDC_CORPONTOS                   1163
#define IDC_DESENHARMALHA               1164
#define IDC_CORSECOES                   1165
#define IDC_EQUIDISTANCIACOTAS          1165
#define IDC_COTARMALHA                  1165
#define IDC_CORTEXTO                    1166
#define IDC_EQUICOTAS                   1166
#define IDC_DESENHARPROJETO             1166
#define IDC_EQUIDISTANCIAY              1166
#define IDC_RADIOFUNDO                  1167
#define IDC_CIRCULARSECOES              1167
#define IDC_RADIOPONTOS                 1168
#define IDC_CHE_VARRERTERRENO           1168
#define IDC_RADIO1                      1169
#define IDC_CORPROJETO                  1169
#define IDC_RAABSOLUTO                  1169
#define IDC_PROJETO                     1169
#define IDC_RAD_SECCIONAR               1169
#define IDC_RADCRIAR                    1169
#define IDC_RADIOARESTAS                1170
#define IDC_CORES                       1170
#define IDC_RADIOBORDOS                 1171
#define IDC_RADIOCRISTASPES             1172
#define IDC_RADIOMALHA                  1173
#define IDC_RADIOSECOES                 1174
#define IDC_RADIOTEXTO                  1175
#define IDC_CORPAVIMENTO                1176
#define IDC_RADIOPROJETO                1176
#define IDC_RADIOPAVIM                  1177
#define IDC_RADIOCN                     1177
#define IDC_CORTERRAPLANAGEM            1178
#define IDC_RADIOTERRAPLANAGEM          1179
#define IDC_CORTERRENO                  1180
#define IDC_RADIOTERRENO                1181
#define IDC_DESTERRAPLANAGEM            1183
#define IDC_EQUIMALHA                   1185
#define IDC_CORESGREIDE                 1186
#define IDC_CORRDN                      1187
#define IDC_COORDE                      1188
#define IDC_I                           1189
#define IDC_EDNOVOANGULO                1192
#define IDC_RARLATIVO                   1193
#define IDC_EDANGULOATUAL               1194
#define IDC_TEXTO                       1194
#define IDC_TERRENO                     1195
#define IDC_EDESTACA                    1196
#define IDC_COORDN                      1197
#define IDC_STDESCRICAO                 1198
#define IDC_DESCRICAO1                  1200
#define IDC_BUTCANCELAR                 1201
#define IDC_CHECKGREIDE                 1203
#define IDC_CHECKGEOMETRICO             1204
#define IDC_CHECKSUPERFICIE             1205
#define IDC_DESCRICAOOAE                1206
#define IDC_OK2                         1207
#define IDC_PROGDXFGEO                  1209
#define IDC_MENSGERARDXF                1210
#define IDC_CK_COTARMALHA               1212
#define IDC_COTAR_MALHA                 1212
#define IDC_CHE_AJUSTARCURVAS           1213
#define IDC_EDI_ERROMAXIMO              1214
#define IDC_STA_VALORERRO               1215
#define IDC_RAD_2OFFSETS                1216
#define IDC_RAD_1OFFSET                 1217
#define IDC_RAD_COMPROJETERR            1218
#define IDC_RAD_TODASASSECOES           1219
#define IDC_RAD_COMTERRENO              1220
#define IDC_CHE_TERRENO                 1227
#define IDC_CHECK2                      1228
#define IDC_CHE_PROJETO                 1228
#define IDC_CHE_COTARCN                 1228
#define IDC_PORCDIRET                   1229
#define IDC_TREE                        1230
#define IDC_EDIEQUICN                   1230
#define IDC_STATIC_NOTE                 1231
#define IDC_STAEQUICN                   1231
#define IDC_BUTINICIAR                  1232
#define IDC_PROCALCCN                   1233
#define IDC_BUTPAUSA                    1234
#define IDC_PROGCALCTALUDES             1235
#define IDC_BUTINICIARCALCTAL           1236
#define IDC_PROGCALCLIMPEZA             1237
#define IDC_BUTINICIARCALCLIMPEZA       1238
#define IDC_STAOBS                      1239
#define IDC_STA                         1240
#define IDC_CHE_DESENHARCN              1242
#define IDC_STADESEJAMANTER             1246
#define IDC_RADABRIR                    1247
#define IDC_EQUIDISCN                   1248
#define IDC_PROCALCSUPERF               1250
#define IDC_STAMSGCALCSUPERF            1251
#define IDC_BUTCALCSUPERF               1252
#define IDC_BUTPAUSAR                   1253
#define IDC_EDIEQUIDIS                  1254
#define IDC_STAMENSAGEM                 1255
#define IDC_CHEIGNORAR                  1256
#define IDC_STAMEMSAGEM                 1257
#define IDC_PROGRESSO                   10070
#define IDC_DESBORDOS                   10071
#define IDC_REMOVE2                     10072
#define IDC_CALCSOCOTA                  10161
#define ID_PROJ_NEW                     32771
#define ID_PROJ_OPEN                    32772
#define ID_PROJ_ABRIR                   32772
#define ID_BUTTON32773                  32773
#define ID_ARQ_ABRIR                    32775
#define ID_FECHAR                       32779
#define ID_NOVALINHA                    32779
#define ID_GRAVAR                       32780
#define ID_EXLINHA                      32780
#define ID_AJUDAESPECIFICA              32781
#define ID_AJUDAGERAL                   32782
#define ID_CORTAR                       32783
#define ID_COPIAR                       32784
#define ID_COLAR                        32785
#define ID_PROC_ANTE                    32787
#define ID_ARQ_NOVO                     32790
#define ID_SALVARTUDO                   32793
#define ID_PROJ_NOVO                    32796
#define ID_BUTTON32797                  32797
#define ID_BUTTON32798                  32798
#define ID_PROC_PROX                    32800
#define ID_CONFIG_PROJ                  32801
#define ID_PRINT                        32802
#define ID_BUTTON32803                  32803
#define ID_BUTTON32804                  32804
#define ID_PROJREC2                     32805
#define ID_PROJREC3                     32806
#define ID_PROJREC5                     32808
#define ID_MARCAR                       32809
#define ID_PROJREC6                     32810
#define ID_PROJREC4                     32811
#define ID_EXCUIRMARCAS                 32812
#define ID_PROJREC1                     32813
#define ID_BUTTON32815                  32815
#define ID_PROJ_FECHAR                  32816
#define ID_FILE_ABRIR                   32817
#define ID_JANELA_CENTRAR               32817
#define ID_FILE_SAVE_ALL                32818
#define ID_PROJ_CLOSE                   32819
#define ID_BUTTON32822                  32822
#define ID_BUTTON32823                  32823
#define ID_PROX_JANELA                  32826
#define ID_JANELA_ANTERIOR              32827
#define ID_JANELA_ANT                   32828
#define ID_PROCURAR                     32829
#define ID_CALCTERRENO                  32830
#define ID_MEDIO_CALCULARAMEDIO         32831
#define ID_MEDIO_NOVA                   32832
#define ID_MEDIO_ABRIR                  32833
#define ID_MEDIO_FECHAR                 32834
#define ID_CLCULOS_CALCULATANOTADESERVIO 32835
#define ID_CLCULOS_CALCULAROSDADOSGEOMTRICOS 32836
#define ID_BUTTON32848                  32848
#define ID_BUTTON32849                  32849
#define ID_MENOS                        32851
#define ID_BUTPROXIMA                   32852
#define ID_BUTANTERIOR                  32853
#define ID_VEZES                        32854
#define ID_DIVIDE                       32855
#define ID_MAIS                         32856
#define ID_BUTTON32858                  32858
#define ID_PRIMEIRASECAO                32861
#define ID_ULTIMASECAO                  32862
#define ID_BUTTON32863                  32863
#define ID_BUTTON32864                  32864
#define ID_BUTTON32865                  32865
#define ID_GRAVARDESSECAO               32870
#define ID_BUTTON32872                  32872
#define ID_DESLXDIR                     32873
#define ID_DESLOCAXESQ                  32874
#define ID_CALCOFFSETS                  32878
#define ID_BUTTON32898                  32898
#define ID_BUTTON32899                  32899
#define ID_BUTTON32913                  32913
#define ID_BUTTON32922                  32922
#define ID_CONFIGTOOLSEC                32928
#define ID_CONFGREIDE                   32930
#define ID_BUTTON32932                  32932
#define ID_DESENHOS_PERFIL              32933
#define ID_DESENHOS_SECOES              32934
#define ID_DESENHOS_GREIDE              32935
#define ID_BUTTON32940                  32940
#define ID_MEDIR_CONFIGURAR             32941
#define ID_RESTAURARSECAO               32942
#define ID_DESSECVOLTAR                 32943
#define ID_DESGREVOLTAR                 32944
#define ID_CALCULO_VOLUMES              32945
#define ID_GRAVARPERFIL                 32947
#define ID_CALCVOLUMES                  32949
#define ID_SUPERFCIE_GERAR              32950
#define ID_TERRENO_SECCIONAR            32951
#define ID_TERRENO_ACIDENTESTOPOGRFICOS 32952
#define ID_EDITAR_PONTOS_GEO            32953
#define ID_CONFDESPONTOSGEO             32954
#define ID_CONFDESGREIDE                32954
#define ID_DESPONVOLTAR                 32955
#define ID_BUTTON32960                  32960
#define ID_ENQUQUADRAR                  32961
#define ID_ENQUADRAR                    32962
#define ID_REDESENHAR                   32963
#define ID_BUTTON32973                  32973
#define ID_BUTROTACIONAR                32974
#define ID_LIMPARRESTAS                 32977
#define ID_DEFINEBORDOS                 32979
#define ID_ACITOPOG                     32982
#define ID_BUTTON32983                  32983
#define ID_BUTTON32984                  32984
#define ID_BUTTON32987                  32987
#define ID_BUTTON32992                  32992
#define ID_BUTTON32993                  32993
#define ID_BUTTON32995                  32995
#define ID_BUTTON32997                  32997
#define ID_BUTTON32998                  32998
#define ID_GERARTERRENO                 33001
#define ID_APARARbORDOS                 33002
#define ID_SECSEMPREVIS_ICONIZAR        33002
#define ID_IRPARAPONTO                  33005
#define ID_MOSTRARTUDO                  33006
#define ID_ALTERNARTITULO               33011
#define ID_ALTERNARTITULOGREIDE         33012
#define ID_BUTFECHar                    33013
#define ID_BUTVISUALIZARTODASECAO       33014
#define ID_RELAT_NOTADESERVI            33015
#define ID_RELAT_PROJETOGEOM            33016
#define ID_RELAT_PROJETOGEOM33017       33017
#define ID_RELAT_CURVASVERTICAIS        33018
#define ID_NOTADESERVI_TERRAPLANAGEM    33019
#define ID_NOTADESERVI_PAVIMENTA        33020
#define ID_RELAT_TERRENOPRIMITIVO       33021
#define ID_RELAT_VOLUMES                33023
#define ID_BUTTON33024                  33024
#define ID_DESENHOS_GERARDXF            33025
#define ID_DESDXFPROGEOM                33028
#define ID_DESDXFGREIDE                 33029
#define ID_DESDXFSECOES                 33030
#define ID_CALCGEOMETRICO               33031
#define ID_BUTTON33032                  33032
#define ID_C33033                       33033
#define ID_TERRENO_GERAR_CN             33034
#define ID_BUTSECAVULSA                 33035
#define ID_Menu                         33036
#define ID_SECOESAVULSAS                33038
#define ID_CALC_SECOES_AVULSAS          33040
#define ID_MOSTSECAVULSAS               33041
#define ID_BUTMOSTSECAVULSAS            33042
#define ID_RELAT_SECAVULSAS             33044
#define ID_CALC_SECOES_TRANSVERSAIS     33052
#define ID_CALC_AREA_TALUDES            33054
#define ID_RELAT_AREA_TALUDES           33056
#define ID_CALC_AREA_LIMPEZA            33058
#define ID_RELAT_AREA_LIMPEZA           33060
#define ID_BUTCNTOPOGRAF                33062
#define ID_BUTBORDOS                    33064
#define ID_BUTSINCRO                    33072
#define ID_BUTLOCK                      33073
#define ID_C_SECCIONAR                  33074
#define ID_TRANCARDESSECOES             33075
#define ID_BUTTON33080                  33080
#define ID_BUTACITOPOG                  33084
#define IDS_SELECT_ENTRY_TO_BE_UPDATED  57656
#define IDS_SELECT_ENTRY_TO_BE_REMOVED  57657
#define IDS_BLANK_CHARS_NOT_ALLOWED     57658
#define IDS_SELECT_ENTRY                57659
#define ID_FINDCOMBO                    57671
#define ID_FINDCOMBO2                   57672
#define IDS_FINDCOMBODES                57673
#define ID_TESTE                        57674
#define ID_TESTE2                       57675
#define ID_FINDRUA                      57676


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        282
#define _APS_NEXT_COMMAND_VALUE         33085
#define _APS_NEXT_CONTROL_VALUE         1258
#define _APS_NEXT_SYMED_VALUE           141
#endif
#endif
